### ISSUE TITLE
Panic after oleutil.CreateObject returned nil, nil

### ISSUE THREAD

**Issue by stevenh** [go-ole/go-ole#122]
We've started to see panics in our WMI code which lists processes after upgrading from go 1.5 to go 1.6.

``` go
goroutine 20 [running]:
panic(0x8c7b60, 0xc082026050)
        /usr/local/go/src/runtime/panic.go:481 +0x3f4
vendor/github.com/go-ole/go-ole.release(0x0, 0x8e7a40)
        vendor/github.com/go-ole/go-ole/iunknown_windows.go:49 +0x1f
vendor/github.com/go-ole/go-ole.(*IUnknown).Release(0x0, 0x0)
        vendor/github.com/go-ole/go-ole/iunknown.go:56 +0x28
panic(0x8c7b60, 0xc082026050)
        /usr/local/go/src/runtime/panic.go:443 +0x4f7
vendor/github.com/go-ole/go-ole.queryInterface(0x0, 0xbe88c0, 0x0, 0x0, 0x0)
        vendor/github.com/go-ole/go-ole/iunknown_windows.go:26 +0x4f
vendor/github.com/go-ole/go-ole.(*IUnknown).QueryInterface(0x0, 0xbe88c0, 0x0, 0x0, 0x0)
        vendor/github.com/go-ole/go-ole/iunknown.go:40 +0x3e
vendor/github.com/StackExchange/wmi.(*Client).Query(0xbe8182, 0xc0823fd800, 0x2ef, 0x7cdc20, 0xc08221ff80, 0x0, 0x0, 0x0, 0x0, 0x0)
        vendor/github.com/StackExchange/wmi/wmi.go:147 +0x3cf
```

The relevant snippet from wmi.go is the following with the panic occuring on unknown.QueryInterface line:

``` go
lock.Lock()
defer lock.Unlock()
runtime.LockOSThread()
defer runtime.UnlockOSThread()

err := ole.CoInitializeEx(0, ole.COINIT_MULTITHREADED)
if err != nil {
        oleerr := err.(*ole.OleError)
        // S_FALSE           = 0x00000001 // CoInitializeEx was already called on this thread
        if oleerr.Code() != ole.S_OK && oleerr.Code() != 0x00000001 {
                return err
        }
} else {
        // Only invoke CoUninitialize if the thread was not initizlied before.
        // This will allow other go packages based on go-ole play along
        // with this library.
        defer ole.CoUninitialize()
}

unknown, err := oleutil.CreateObject("WbemScripting.SWbemLocator")
if err != nil {
        return err
}
defer unknown.Release()

wmi, err := unknown.QueryInterface(ole.IID_IDispatch)
if err != nil {
        return err
}
defer wmi.Release()
```

From the stack unknown is 0x0 (nil) so it appears that oleutil.CreateObject returned nil, nil.

As mentioned this started happening when we upgraded from go 1.5.4 to 1.6.2 so it smells like there may be either some memory corruption happening or the garbage collector is cleaning up unknown while its still required.

Any ideas?

**Comment by mattn** [comment]
do you need to use COINIT_MULTITHREADED ?

**Comment by stevenh** [comment]
That code is from [StackExchange's wmi module](https://github.com/StackExchange/wmi/) not our code, we use it and in turn go-ole.

It's my understanding that they use COINIT_MULTITHREADED to keep performance high and avoid the serialisation of COINIT_APARTMENTTHREADED this was chosen.

I don't believe this should be causing an issue?

**Comment by mattn** [comment]
I did doubt about double-free (calling release twice). So suggested to use COINIT_APARTMENTTHREADED as you did. thanks.

**Comment by stevenh** [comment]
As unknown is a local I can't see a way that Release can be called twice either, but I think its clear from the trace that unknown is nil.

Given that I'm wondering if we're looking at a wrongly sized variable somewhere, so garbage collection is clearing more than it should resulting memory corruption.

What's really frustrating is I can't easily reproduce, seems like it takes up to 3 days of running with this call being made once a minute before we see the issue.

Any ideas on what we could try to help narrow it down @mattn ?

**Comment by stevenh** [comment]
Saying that we added the following code and deployed last night and have results:
```go
        unknown, err := oleutil.CreateObject("WbemScripting.SWbemLocator")
        if err != nil {
                return err
+       } else if unknown == nil {
+               return fmt.Errorf("unknown is nil (%v)", err)
        }
```
We do hit the "unknown is nil" case.

**Comment by stevenh** [comment]
It feels like we're seeing something similar to:
https://github.com/go-ole/go-ole/issues/18

**Comment by stevenh** [comment]
Just to double check I switched to COINIT_APARTMENTTHREADED and removed the wmi locking and we still see instances of both err and unknown being nil
