### ISSUE TITLE
winsock.go exception

### ISSUE THREAD

**Issue by pinke** [go-ole/go-ole#143]
winsock.go exception
go.exe run winsock.go
`panic: compileCallback: input parameter size is wrong

goroutine 1 [running]:
syscall.compileCallback(0x4c6a80, 0x4e385c, 0x1, 0x0)
	G:/soft/go/src/runtime/syscall_windows.go:58 +0x30d
syscall.NewCallback(0x4c6a80, 0x4e385c, 0x447f14)
	G:/soft/go/src/syscall/syscall_windows.go:127 +0x2e
main.main()
	C:/Users/pinke/Desktop/testgo/winsock.go:125 +0x17b
exit status 2`

**Comment by pinke** [comment]
go version go1.8.1 windows/386

**Comment by mattn** [comment]
I don't repro on windows/amd64.

**Comment by robbmcleod** [comment]
I ran into this, the problem is that `syscall` expects all function arguments to be `uintptr` or the same size, which on windows/amd64 is correct for `int` as `int == int64`.  So the function declaration:

    func GetIDsOfNames(this *ole.IUnknown, iid *ole.GUID, wnames []*uint16, namelen int, lcid int, pdisp []int32) uintptr {

is the wrong size on windows/386 for `namelen` and `lcid`.  I think it should be:

    func GetIDsOfNames(this *ole.IUnknown, iid *ole.GUID, wnames []*uint16, namelen *int, lcid *int, pdisp []int32) uintptr {

**Comment by mattn** [comment]
LCID is defined as `typedef DWORD LCID;`. So it should be 32bit. Could you please try below?

```go
func GetIDsOfNames(this *ole.IUnknown, iid *ole.GUID, wnames []*uint16, namelen int, lcid int32, pdisp []int32) uintptr {
```

**Comment by robbmcleod** [comment]
Unfortunately that does not work.  Here is the `compileCallback` implementation (line 42):

https://golang.org/src/runtime/syscall_windows.go

and the part the produces an error:

	for _, t := range ft.in() {
  		if t.size > uintptrSize {
  			panic("compileCallback: input parameter size is wrong")
  		}
  		argsize += uintptrSize
  	}

I am running on amd64, but I have some 32-bit COM objects that I don't have source for.  So I compile as:

    env GOOS=windows GOARCH=386 go build winsock.go

I can't figure out how to expose `eface` from `runtime` to debug.

**Comment by jacobsantos** [comment]
Unsure if this will still be an issue. Tests will be added to verify this behavior on 32-bit and 64-bit architectures with Test COM Server.
