### ISSUE TITLE
IE Example does not work

### ISSUE THREAD

**Issue by bcvery1** [go-ole/go-ole#163]
**OS**: Windows 7 Professional 64bit
**IE Version**: 11.0.9600.19002
**Go version**: `go version go1.10 windows/amd64`
**go env**:
```
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\bcvery1\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\bcvery1\go
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
```

I'm trying to run the IE example provided [here](https://github.com/go-ole/go-ole/blob/master/example/ie/ie.go).

The output I get is:
```
$ go run ie.go
panic: Unknown name.

goroutine 1 [running]:
github.com/go-ole/go-ole/oleutil.MustCallMethod(0x2f1c000, 0x4d532b, 0x4, 0xc04206ff48, 0x1, 0x1, 0xc042154060)
        C:/Users/bcvery1/go/src/github.com/go-ole/go-ole/oleutil/oleutil.go:58 +0xe7
main.main()
        C:/Users/bcvery1/go/src/github.com/go-ole/go-ole/example/ie/ie.go:29 +0x28b
exit status 2
```

The line that appears to be failing is:
```go
	// set 'golang' to text box.
	oleutil.MustCallMethod(window, "eval", "document.getElementsByName('q')[0].value = 'golang'")
```
And looking through the source it appears that it does not like the string `"eval"`.  Is there a list of valid "names" which can be used?

---

I had a look through closed issues to see if I could find anything related to this problem.  I found #1 which has IE code in.  Having changed `"github.com/mattn/go-ole"` to `ole "github.com/go-ole/go-ole"`, **this code** works as expected.

**Comment by mattn** [comment]
Hmm, `oleutil.MustCallMethod(window, "alert", "1")` works well.

**Comment by bcvery1** [comment]
@mattn Yeah, that works fine for me too
The "names" that are working from issue #1 are:
```go
  item := oleutil.MustCallMethod(anchors, "item", i).ToIDispatch()
  link := oleutil.MustCallMethod(elem, "getAttribute", "href").ToString()
```

Really hoping to find the right command/name to evaluate JavaScript

**Comment by bcvery1** [comment]
@mattn any other ideas about how I might either
 1) Evaluate JavaScript
 2) Insert a `<script>...</script>` tag to the body?

I can't find any working examples of the first, and no examples of the second

**Comment by mattn** [comment]
How about this?

```go
// +build windows

package main

import (
	"time"

	ole "github.com/go-ole/go-ole"
	"github.com/go-ole/go-ole/oleutil"
)

func main() {
	ole.CoInitialize(0)
	unknown, _ := oleutil.CreateObject("InternetExplorer.Application")
	ie, _ := unknown.QueryInterface(ole.IID_IDispatch)
	oleutil.PutProperty(ie, "Visible", true)
	oleutil.CallMethod(ie, "Navigate", "http://www.google.com")
	for {
		if oleutil.MustGetProperty(ie, "Busy").Val == 0 {
			break
		}
	}

	time.Sleep(1e9)

	document := oleutil.MustGetProperty(ie, "document").ToIDispatch()

	// set 'golang' to text box.
	elems := oleutil.MustCallMethod(document, "getElementsByName", "q").ToIDispatch()
	q := oleutil.MustCallMethod(elems, "item", 0).ToIDispatch()
	oleutil.MustPutProperty(q, "value", "golang")

	// click btnG.
	elems = oleutil.MustCallMethod(document, "getElementsByTagName", "input").ToIDispatch()
	length := int(oleutil.MustGetProperty(elems, "length").Val)
	for i := 0; i < length; i++ {
		btn := oleutil.MustCallMethod(elems, "item", i).ToIDispatch()
		typ := oleutil.MustGetProperty(btn, "type").ToString()
		val := oleutil.MustGetProperty(btn, "value").ToString()
		if typ == "submit" && val == "I'm Feeling Lucky" {
			oleutil.MustCallMethod(btn, "click")
			break
		}
	}
}
```

**Comment by mattn** [comment]
Google seems change page layouts.

**Comment by bcvery1** [comment]
That code works - I couldn't see a contributes doc, do you accept PRs, if I were to update the "IE" example using the above code?
