### ISSUE TITLE
help use method

### ISSUE THREAD

**Issue by veliev** [go-ole/go-ole#188]
Help with your library convert xlsx to pdf
```
Set XLWkbk = XL.Workbooks.Open("C:\\2.xlsx", False)
XLWkbk.ExportAsFixedFormat 0, "C:\\2.pdf", 1, false, false
```
I tried
 ```
ole.CoInitialize(0)
unknown, _ := oleutil.CreateObject("Excel.Application")
excel, _ := unknown.QueryInterface(ole.IID_IDispatch)
oleutil.PutProperty(excel, "Visible", false)
oleutil.PutProperty(excel, "DisplayAlerts", false)
oleutil.PutProperty(excel, "ScreenUpdating", false)
workbooks := oleutil.MustGetProperty((*ole.IDispatch)(excel), "Workbooks")
workbook := oleutil.MustCallMethod(workbooks.ToIDispatch(), "Open", "C:\\2.xlsx")
oleutil.CallMethod(workbook.ToIDispatch(), "ExportAsFixedFormat", "0","C:\\1.pdf","1","false","false")
oleutil.MustCallMethod(workbook.ToIDispatch(), "Close")
oleutil.CallMethod(excel, "Quit")
workbooks.ToIDispatch().Release()
excel.Release()
ole.CoUninitialize()
```
Dont work
Please help me

**Comment by veliev** [comment]
Or
```
sheet := oleutil.MustGetProperty(workbook.ToIDispatch(), "Worksheets", 1)
oleutil.MustCallMethod(sheet.ToIDispatch(), "ExportAsFixedFormat", "C:\\2.xps", "xlTypeXPS")
```
error

> panic: Несовпадение типов.
> 
> goroutine 1 [running]:
> github.com/go-ole/go-ole/oleutil.MustCallMethod(0x952b7c, 0x4ca66c, 0x13, 0x1446dfbc, 0x2, 0x2, 0x14452460)
>         C:/Users/IVC-TVeliev/go/pkg/mod/github.com/go-ole/go-ole@v1.2.4/oleutil/oleutil.go:58 +0x9f
> main.main()
>         C:/Users/IVC-TVeliev/go/src/awesome/test.go:23 +0x37b
> exit status 2
