### ISSUE TITLE
Allow []uint16/[]int32/etc arrays in PutProperty() 

### ISSUE THREAD

**Issue by gabriel-samfira** [go-ole/go-ole#194]
I am trying to set a ```[]uint16``` () property on an instance of the ```Msvm_VirtualSystemSettingData``` class, however I get the following panic:

```bash
panic: unknown type

goroutine 1 [running]:
github.com/go-ole/go-ole.invoke(0xb4e388, 0x401800001, 0xc00007db58, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/gabriel/golang/pkg/mod/github.com/go-ole/go-ole@v1.2.4/idispatch_windows.go:165 +0x184c
github.com/go-ole/go-ole.(*IDispatch).Invoke(...)
        /home/gabriel/golang/pkg/mod/github.com/go-ole/go-ole@v1.2.4/idispatch.go:27
github.com/go-ole/go-ole.(*IDispatch).InvokeWithOptionalArgs(0xb4e388, 0x54cc15, 0x9, 0x510004, 0xc00007db58, 0x1, 0x1, 0x3, 0xc00010a020, 0x0)
        /home/gabriel/golang/pkg/mod/github.com/go-ole/go-ole@v1.2.4/idispatch.go:71 +0x103
github.com/go-ole/go-ole/oleutil.PutProperty(...)
        /home/gabriel/golang/pkg/mod/github.com/go-ole/go-ole@v1.2.4/oleutil/oleutil.go:79
go-wmi/wmi.(*Result).Set(0xc000004f00, 0x54cc15, 0x9, 0xc00007db58, 0x1, 0x1, 0x0, 0x0)
        /home/gabriel/golang/src/github.com/gabriel-samfira/go-wmi/wmi/wmi.go:236 +0x107
go-wmi/virt/vm.(*VirtualMachine).SetBootOrder(0xc00005e930, 0xc00007dbf8, 0x4, 0x4, 0x0, 0x0)
        /home/gabriel/golang/src/github.com/gabriel-samfira/go-wmi/virt/vm/vm.go:328 +0xd9
go-wmi/virt/vm.(*Manager).CreateVM(0xc000032310, 0x54c20c, 0x4, 0xc00, 0x3, 0x0, 0xc00007def0, 0x3, 0x3, 0x551c8f, ...)
        /home/gabriel/golang/src/github.com/gabriel-samfira/go-wmi/virt/vm/vm.go:281 +0x5b0
main.main()
        /home/gabriel/golang/src/github.com/gabriel-samfira/go-wmi/examples/create_vm/create_vm.go:38 +0x286
``` 

The class documentation is here: https://docs.microsoft.com/en-us/windows/win32/hyperv_v2/msvm-virtualsystemsettingdata

Here is the ```GetText(1)``` result for that class:

https://paste.ubuntu.com/p/K5Jcwbm3rW/

Any chance to add ```[]int16/32/64``` and ```[]uint16/32/64``` to the ```invoke()``` function in ```idispatch_windows.go``` ?

**Comment by dong0812** [comment]
I have a same problem
