### ISSUE TITLE
oleutil.ConnectObject: panic: compileCallback: expected function with one uintptr-sized result

### ISSUE THREAD

**Issue by iamcalledrob** [go-ole/go-ole#261]
oleutil.ConnectObject appears to not work.
go version: `go version go1.23.0 windows/amd64`

Issue happens on latest release (1.3.0) and master.

This seems to be due to the signature of `dispQueryInterface` in connection.go, which is returning a uint32, whereas syscall.NewCallback wants a uintptr-sized return type.

[`func dispQueryInterface(this *ole.IUnknown, iid *ole.GUID, punk **ole.IUnknown) uint32`](https://github.com/go-ole/go-ole/blob/6c7f9027aa642e576d44a9f87344e11d1413ac68/oleutil/connection.go#L30)

```
panic: compileCallback: expected function with one uintptr-sized result

goroutine 1 [running]:
syscall.compileCallback({0x8fbe00?, 0x92c280?}, 0xb0?)
        C:/Program Files/Go/src/runtime/syscall_windows.go:291 +0x4e5
syscall.NewCallback(...)
        C:/Program Files/Go/src/syscall/syscall_windows.go:216
github.com/go-ole/go-ole/oleutil.ConnectObject(0x23ee1d6d870, 0xc00000a2e0, {0x90e980, 0xc000109f20})

        C:/Users/admin/go/pkg/mod/github.com/go-ole/go-ole@v1.3.1-0.20241107203841-6c7f9027aa64/oleutil/connection_windows.go:37 +0x1a7
main.main()
```

**Comment by jacobsantos** [comment]
Fixed on v2 branch. Need to apply to v1.3 (soon to be v1.4).

**Comment by jacobsantos** [comment]
Added to master and should be in v1.4 when it is released.
